version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  reviewers:
  - masahiro04
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  reviewers:
  - masahiro04
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: codecov
    versions:
    - ">= 0.2.14.a, < 0.2.15"
  - dependency-name: rails
    versions:
    - "> 6.0.0, < 6.1"
  - dependency-name: oauth2
    versions:
    - 1.4.5
  - dependency-name: aws-partitions
    versions:
    - 1.427.0
    - 1.431.0
    - 1.433.0
    - 1.435.0
    - 1.437.0
    - 1.438.0
    - 1.444.0
    - 1.448.0
  - dependency-name: aws-sdk-kms
    versions:
    - 1.43.0
  - dependency-name: oj
    versions:
    - 3.11.3
  - dependency-name: aws-sigv4
    versions:
    - 1.2.3
  - dependency-name: aws-eventstream
    versions:
    - 1.1.1
  - dependency-name: aws-sdk-core
    versions:
    - 3.112.0
  - dependency-name: formtastic
    versions:
    - 4.0.0
  - dependency-name: i18n
    versions:
    - 1.8.8
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.4.0
  - dependency-name: bootsnap
    versions:
    - 1.7.0
  - dependency-name: nokogiri
    versions:
    - 1.11.3
  - dependency-name: marcel
    versions:
    - 1.0.0
  - dependency-name: mimemagic
    versions:
    - 0.3.10
    - 0.3.6
  - dependency-name: active_interaction
    versions:
    - 4.0.0
  - dependency-name: rails
    versions:
    - 6.1.0
