version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 30
  target-branch: main
  reviewers:
  - masahiro04
  ignore:
  - dependency-name: webpack
    versions: ["4.x", "5.x"]
  - dependency-name: webpack-cli
    versions: ["4.x", "5.x"]
  - dependency-name: webpack-dev-server
    versions: ["4.x"]
  - dependency-name: '@fortawesome/fontawesome-free'
    versions: ["6.x"]
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 30
  target-branch: main
  reviewers:
  - masahiro04
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.4.0
