exclude:
  - 'node_modules/**/*'
  - 'vendor/**/*'
  - 'app/views/admin/orders/_react_datepicker.html.slim' # FIXME

linters:
  LineLength:
    enabled: true
    max: 300
  RuboCop:
    enabled: true
    config_file: '.rubocop.yml'
  NestedControlStatements:
    enabled: false
  ClassAttributeWithStaticValue:
    enabled: true
  LawOfDemeter:
    enabled: true
