version: "3.8"



networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16

services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maching_system_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      test:
        ipv4_address: 172.30.0.5

  # redis:
  #   image: redis:5-alpine
  #   volumes:
  #     - redis:/data

  web: &web
    build: .
    image: app:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
      - packs_test:/app/public/packs-test
    tmpfs:
      - /tmp
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"
      WD_INSTALL_DIR: "/usr/local/bin"
      HISTFILE: "/app/log/.bash_history"
      EDITOR: "vi"
      DATABASE_HOST: 'db'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      LOCAL: 'true'
      # REDIS_URL: "redis://redis:6379/"
      RAILS_MASTER_KEY:
    depends_on:
      - db
      # - redis
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3000:3000"]
    user: root
    working_dir: /app
    networks:
      test:
        ipv4_address: 172.30.0.6


  webpacker:
    <<: *web
    command: "bin/webpack-dev-server"
    ports:
      - '3035:3035'
    stdin_open: true
    tty: true
    # tty: false
    # stdin_open: false
    depends_on:
      - web
    networks:
      test:
        ipv4_address: 172.30.0.7


  # worker:
  #   <<: *web
  #   command: ["bin/rails", "jobs:work"]
  #   expose: []
  #   ports: []
  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - '4444:4444'
    networks:
      test:
        ipv4_address: 172.30.0.8


volumes:
  postgres:
  # redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
  packs_test:
