#version: "3.8"
# version is ingore for latest docker-compose

services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maching_system_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    image: app:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - vendor:/app/vendor/
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
      - packs_test:/app/public/packs-test
      - certs:/app/config/certs
    tmpfs:
      - /tmp
    environment:
#      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"
      WD_INSTALL_DIR: "/usr/local/bin"
      HISTFILE: "/app/log/.bash_history"
      EDITOR: "vi"
#      DATABASE_HOST: 'db'
#      DATABASE_USER: 'postgres'
#      DATABASE_PASSWORD: 'postgres'
#      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      LOCAL: 'true'
      RAILS_MASTER_KEY:
#    depends_on:
#      - db
#    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    expose: ["3000"]
#    ports: ["3000:3000"]
    ports:
      - "3000:3000"
      - "8443:8443"
    user: root
    working_dir: /app

#  cron_job:
#    <<: *web
#    command: /bin/sh -c "bundle exec whenever --update-crontab && cron -f"
#    expose: []
#    ports: []
#    depends_on:
#      - web

#  webpacker:
#    <<: *web
#    command: "bin/webpack-dev-server"
#    ports:
#      - '3035:3035'
#    stdin_open: true
#    tty: true
#    # tty: false
#    # stdin_open: false
#    depends_on:
#      - web

#  worker:
#    <<: *web
#    command: ["bin/rails", "jobs:work"]
#    expose: []
#    ports: []

  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - '4444:4444'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"  # mail web page port
      - "1025:1025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

volumes:
  postgres:
  vendor:
  node_modules:
  rails_cache:
  packs:
  packs_test:
  maildir:
  certs: