class AddFieldsToOrders < ActiveRecord::Migration[7.2]
  def change
    add_column :orders, :is_managercontrol, :boolean, default: false, null: false, comment:'運営管理フラグ'
    add_column :orders, :order_create_source_code, :string, null: true, comment:'案件作成元区分'
    add_column :orders, :manage_company_code, :string, null: true, comment:'案件管理会社区分'
    add_column :orders, :business_integration_flag, :boolean, default: true, null: false, comment:'業務統合フラグ'
    add_column :orders, :is_withholding_tax, :boolean, default: false, null: false, comment:'源泉徴収フラグ'
    add_column :orders, :status_updated_at, :datetime, null: true, comment:'ステータス更新日'
    add_column :orders, :facility_request_approved_at, :datetime, null: true, comment:'正式依頼承認日（ダウンロード日）'
    add_column :orders, :approved_total_partner_payment, :integer, null: true, comment:'正式依頼承認時のパートナー謝礼全体（税込）'
    add_column :orders, :final_report_approved_at, :datetime, null: true, comment:'施設の終了報告の承認日'
    add_column :orders, :tax_rate, :decimal, precision: 15, scale: 3, null: true, comment:'消費税率'
    add_column :orders, :tax_amount, :integer, null: true, comment:'消費税'
    add_column :orders, :amount_with_tax, :integer, null: true, comment:'パートナー謝礼（税込）'
    add_column :orders, :total_material_amount, :integer, null: true, comment:'材料費合計'
    add_column :orders, :total_additional_facility_fee, :integer, null: true, comment:'追加施設費合計'
    add_column :orders, :total_partner_payment_with_tax, :integer, null: true, comment:'パートナー謝礼全体（税込）'
    add_column :orders, :partner_fee_rate, :decimal, precision: 15, scale: 3, null: true, comment:'パートナー手数料率'
    add_column :orders, :additional_facility_fee_commission, :integer, null: true, comment:'追加施設手数料'
    add_column :orders, :total_additional_facility_fee_commission, :integer, null: true, comment:'追加施設手数料計'
    add_column :orders, :partner_invoice_registration_flag, :boolean, default: false, null: false, comment:'パートナーインボイス登録フラグ'
    add_column :orders, :non_invoice_partner_fee_rate, :decimal, precision: 15, scale: 3, null: true, comment:'インボイス非登録パートナー手数率'
    add_column :orders, :non_invoice_partner_fee, :integer, null: true, comment:'インボイス非登録パートナー手数料'
    add_column :orders, :zoom_rental_fee, :integer, null: true, comment:'zoomレンタル料'
    add_column :orders, :recreation_kind, :integer, null: true, comment:'レクマスタ、レク種類'
    add_column :orders, :is_zoom_rental, :boolean, default: false, null: false, comment:'zoomレンタルフラグ'
    add_column :orders, :zoom_rental_actual_fee, :integer, null: true, comment:'zoomレンタル使用料金'
    add_column :orders, :partner_service_fee, :integer, null: true, comment:'パートナーサービス利用料'
    add_column :orders, :partner_deduction_subtotal, :integer, null: true, comment:'パートナー控除小計'
    add_column :orders, :facility_fee_rate, :decimal, precision: 15, scale: 3, null: true, comment:'施設手数料率'
    add_column :orders, :facility_fee_base_amount, :integer, null: true, comment:'施設手数料計算金額'
    add_column :orders, :facility_fee, :integer, null: true, comment:'施設手数料（税込）'
    add_column :orders, :facility_service_fee, :integer, null: true, comment:'施設サービス利用料'
    add_column :orders, :facility_fee_subtotal, :integer, null: true, comment:'施設手数料小計'
    add_column :orders, :withholding_tax_rate, :decimal, precision: 15, scale: 3, null: true, comment:'源泉徴収税率'
    add_column :orders, :withholding_tax_amount, :integer, null: true, comment:'源泉徴収税額'
    add_column :orders, :specific_facility_plan_management_code, :string, null: true, comment:'特定施設プラン管理コード'
    add_column :orders, :partner_payment_amount, :integer, null: true, comment:'パートナー支払額'
    add_column :orders, :gross_profit_incl_tax, :integer, null: true, comment:'粗利（税込）'
    add_column :orders, :gross_profit_margin, :decimal, precision: 15, scale: 3, null: true, comment:'粗利率'
    add_column :orders, :facility_billing_amount, :integer, null: true, comment:'施設請求額'
  end
end

