name: Deploy weldev to AWS ECR

env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  branch: ${{ github.ref_name }}
  awsuser: ${{ secrets.AWS_USER }}
  awshost: ${{ secrets.AWS_HOST }}
  awspkey: ${{ secrets.AWS_PRIVATE_KEY }}
  awsuid: ${{ secrets.AWS_UID }}

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Check aws deploy target branch
        run: |
          if [[ "$branch" == "welbing" ]]; then
            exit 0
          fi
          if [[ "$branch" == "weldev" ]]; then
            exit 0
          fi
          exit 1
      - name: check branch name
        run: echo "${{ github.ref_name }}"
        env:
          branch: ${{ github.ref_name }}
      # リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}  # weldev内のブランチをビルド
      #    sparse-checkout: |
      #      app  # app ディレクトリのみチェックアウト
      #    sparse-checkout-cone-mode: false
      # Amazon ECR へのログイン
      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 167437647770.dkr.ecr.ap-northeast-1.amazonaws.com

      # Docker イメージをビルド
      - name: Build Docker image
        run: |
          docker build -t $branch . # rootディレクトリの Dockerfile を使用

      # Docker イメージに latestタグを付ける
      - name: Tag Docker image
        run: |
          target="167437647770.dkr.ecr.ap-northeast-1.amazonaws.com/${branch}:latest"
          docker tag "${branch}:latest" $target

      # push to Amazon ECR 
      - name: Push Docker image to Amazon ECR
        run: |
          echo $branch
          target="167437647770.dkr.ecr.ap-northeast-1.amazonaws.com/${branch}:latest"
          echo $target
          docker push $target

      # test : ec2 deploy
      - name: ec2 deploy
        run: |
          echo ${awspkey} > private_key
          chmod 600
          ssh -oStrictHostKeyChecking=no ${awsuser}@${awshost} -i private_key "docker pull ${awsuid}.dkr.ecr.ap-northeast-1.amazonaws.com/${branch} && docker run -p 8443:8443 -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -it ${awsuid}.dkr.ecr.ap-northeast-1.amazonaws.com/${branch}"
