name: Deploy weldev to AWS ECR

env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check aws deploy target branch
        run: |
          BRANCHS=$( git branch --contains ${{ github.ref_name }} )
          set -- $BRANCHS
          for BRANCH in $BRANCHS ; do
            if [[ "$BRANCH" == "welbing" ]]; then
              exit 0
            fi
            if [[ "$BRANCH" == "weldev" ]]; then
              exit 0
            fi
          done
          exit 1
	  # weldev or welbingの場合、awsへpush
      - name: check branch name
        run: echo "${{ github.ref_name }}"
	env:
	 branch: ${{ github.ref_name }}
      # リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}  # weldev内のブランチをビルド
      #    sparse-checkout: |
      #      app  # app ディレクトリのみチェックアウト
      #    sparse-checkout-cone-mode: false
      # Amazon ECR へのログイン
      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 167437647770.dkr.ecr.ap-northeast-1.amazonaws.com

      # Docker イメージをビルド
      - name: Build Docker image
        run: |
          docker build -t weldev . # rootディレクトリの Dockerfile を使用

      # Docker イメージに latestタグを付ける
      - name: Tag Docker image
        run: |
          docker tag weldev:latest 167437647770.dkr.ecr.ap-northeast-1.amazonaws.com/weldev:latest

      # Amazon ECR へ Push
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 167437647770.dkr.ecr.ap-northeast-1.amazonaws.com/weldev:latest
